# Generated by Django 2.2.7 on 2019-12-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=50)),
                ('description_classe', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_courant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Classe')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('1', ' '), ('2', 'Garcon'), ('3', 'Fille')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('address', models.CharField(default='Not Set', max_length=150)),
                ('est_etudiant', models.BooleanField(default=True)),
                ('CNE', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intitu_filiere', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Niveau'),
        ),
    ]
