# Generated by Django 2.2.7 on 2019-12-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='id',
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom_classe',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe_courant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='etudiant.Classe'),
        ),
    ]
