# Generated by Django 2.2.7 on 2019-12-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_auto_20191205_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='classe_courant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Classe'),
        ),
    ]
