# Generated by Django 2.2.7 on 2019-12-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_auto_20191205_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classe_courant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.Classe'),
        ),
    ]
