# Generated by Django 2.2.7 on 2019-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_auto_20191205_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('1', ' '), ('Garcon', 'Garcon'), ('Fille', 'Fille')], max_length=10),
        ),
    ]
